---
abstract: 'Load a web service and its dependencies for XML::Compile::WSDL11'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  CHI: '0'
  Carp: '0'
  Const::Fast: '0'
  File::Spec: '0'
  HTTP::Response: '0'
  HTTP::Status: '0'
  IO::Handle: '0'
  IO::Prompt::Tiny: '0'
  IPC::Open3: '0'
  Path::Tiny: '0'
  Scalar::Util: '0'
  Test::LWP::UserAgent: '0'
  Test::More: '0.94'
  Test::Most: '0'
  Test::TempDir::Tiny: '0'
  URI::file: '0'
  WWW::Mechanize::Cached: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.030, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-CompileX-Schema-Loader
requires:
  HTTP::Exception: '0'
  LWP::UserAgent: '0'
  List::MoreUtils: '0'
  Modern::Perl: '0'
  Moo: '0'
  MooX::Types::MooseLike::Base: '0'
  URI: '0'
  XML::Compile::SOAP11: '0'
  XML::Compile::SOAP::Util: '0'
  XML::Compile::Transport::SOAPHTTP: '0'
  XML::Compile::Util: '0'
  XML::Compile::WSDL11: '0'
  XML::LibXML: '0'
  perl: '5.010'
  utf8: '0'
resources:
  bugtracker: https://github.com/mjgardner/xml-compilex-schema-loader/issues
  homepage: https://github.com/mjgardner/xml-compilex-schema-loader
  repository: https://github.com/mjgardner/xml-compilex-schema-loader.git
version: '0.002'
